import React from 'react';
import ErrorBoundary from './ErrorBoundary';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
Enzyme.configure({ adapter: new Adapter() });

let wrapper = {}

beforeEach(() => {
  wrapper = Enzyme.mount(
    <ErrorBoundary >
      throw new Error('Error thrown from problem child');
      return <div>Error</div>;
    </ErrorBoundary>
  );
});

it('displays error message on error generated by child', () => {
  wrapper.setState({ hasError: true });
  expect(wrapper.find('h1').text()).toEqual('Something went wrong.');
});
